source ~/.config/nvim/packer.vim
source ~/.config/nvim/basic.vim
source ~/.config/nvim/keymaps.vim
source ~/.config/nvim/session.vim
source ~/.config/nvim/dashboard.vim
source ~/.config/nvim/visual.vim
source ~/.config/nvim/lsp.vim
source ~/.config/nvim/cmp.vim
source ~/.config/nvim/neo-tree.vim
